import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
// import ConvexClientProvider  from "../provider/convex-client-provider"; 
// // import Provider from "@/provider/provider";
const inter = Inter({ subsets: ["latin"] });



// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (

//     <html lang="en">
//       {/* <meta httpEquiv="Content-Security-Policy" content="script-src 'self' https://scdn.clerk.com/; ..." /> */}
//       {/* className={inter.className} */}
//       <body >
//       <ConvexClientProvider>
//         {children}
//       </ConvexClientProvider>
//         </body>
//     </html>
 
//   );
// }




import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}